import { ProductModel } from "./models/ProductModel";

export const womensProducts: Array<ProductModel> = [
    {name: "bluza czarna", image: "/products/female/blouse_black.jpg", price:99.99},
    // {name: "bluza niebieska", image:"./products/female/blouse_blue.jpg", price:89.99},
    {name: "bluza pomarańczowa", image:"./products/female/blouse_orange.jpg", price:89.99},
    {name: "bluza różowa", image:"./products/female/blouse_pink.jpg", price:79.99},
    {name: "bluza czerwona", image:"./products/female/blouse_red.jpg", price:109.99},
    {name: "bluza żółta", image:"./products/female/blouse_yellow.jpg", price:89.99},
    {name: "kaszkiet", image:"./products/female/cap_1.jpg", price:49.99},
    {name: "sukienka czarna ", image:"/products/female/dress_black.jpg", price:69.99},
    {name: "sukienka kwiecista czarna", image:"/products/female/dress_floral_black.jpg", price:69.99},
    {name: "sukienka kwiecista czerwona", image:"/products/female/dress_floral_red.jpg", price:69.99},
    {name: "sukienka czerwona", image:"/products/female/dress_red.jpg", price:69.99},
    {name: "sukienka pasiasta", image:"/products/female/dress_striped.jpg", price:69.99},
    {name: "sukienka krótka biała", image:"/products/female/dress_white_short.jpg", price:69.99},
    {name: "kapelusz letni", image:"/products/female/hat_summer.jpg", price:69.99},
    {name: "kurtka czarna", image:"/products/female/jacket_black.jpg", price:69.99},
    {name: "kurtka szara", image:"/products/female/jacket_grey.jpg", price:69.99},
    {name: "kurtka jeansowa", image:"/products/female/jacket_jeans_1.jpg", price:69.99},
    {name: "kurtka jeansowa", image:"/products/female/jacket_jeans_2.jpg", price:69.99},
    {name: "kurtka jeansowa", image:"/products/female/jacket_jeans_3.jpg", price:69.99},
    {name: "kurtka jeansowa", image:"/products/female/jacket_jeans_4.jpg", price:69.99},
    {name: "kurtka napisy", image:"/products/female/jacket_streetwear.jpg", price:69.99},
    {name: "kurtka biała", image:"/products/female/jacket_white.jpg", price:69.99},
    {name: "sweter różowy", image:"/products/female/jumper_pink.jpg", price:69.99},
    {name: "spodnie czerwone", image:"/products/female/pants_red.jpg", price:69.99},
    {name: "koszula różowa", image:"/products/female/shirt_pink.jpg", price:69.99},
    {name: "koszula biała", image:"/products/female/shirt_white.jpg", price:69.99},
    {name: "spódnica kraciasta", image:"/products/female/skirt_checked.jpg", price:69.99},
    {name: "spódnica długa", image:"/products/female/skirt_long.jpg", price:69.99},
    {name: "spódnica krótka czerwona", image:"/products/female/skirt_red_short.jpg", price:69.99},
    {name: "okulary przeciwsłoneczne", image:"/products/female/sunglasses_1.jpg", price:69.99},
    {name: "podkoszulek animal love", image:"/products/female/tshirt_animal_love.jpg", price:69.99},
    {name: "podkoszulek beatles", image:"/products/female/tshirt_beatles.jpg", price:69.99},
    {name: "podkoszulek czarny", image:"/products/female/tshirt_black.jpg", price:69.99},
    {name: "podkoszulek czarny", image:"/products/female/tshirt_black_2.jpg", price:69.99},
    {name: "podkoszulek czarny", image:"/products/female/tshirt_black_3.jpg", price:69.99},
    {name: "podkoszulek czarny", image:"/products/female/tshirt_black_4.jpg", price:69.99},
    {name: "podkoszulek czarny", image:"/products/female/tshirt_black_5.jpg", price:69.99},
    {name: "podkoszulek czarny", image:"/products/female/tshirt_black_6.jpg", price:69.99},
    {name: "podkoszulek czarny", image:"/products/female/tshirt_black_bones.jpg", price:69.99},
    {name: "podkoszulek kwiaty", image:"/products/female/tshirt_flowers.jpg", price:69.99},
    {name: "podkoszulek journey", image:"/products/female/tshirt_journey.jpg", price:69.99},
    {name: "podkoszulek leave the road", image:"/products/female/female/tshirt_leave_the_road.jpg", price:69.99},
    {name: "podkoszulek długi", image:"/products/female/tshirt_long.jpg", price:69.99},
    {name: "podkoszulek los angeles", image:"/products/female/tshirt_los_angeles.jpg", price:69.99},
    {name: "podkoszulek", image:"/products/female/tshirt_photo.jpg", price:69.99},
    {name: "podkoszulek kolorowy", image:"/products/female/tshirt_printed.jpg", price:69.99},
    {name: "podkoszulek pulp fiction", image:"/products/female/tshirt_pulp_fiction.jpg", price:69.99},
    {name: "podkoszulek not today", image:"/products/female/tshirt_snake_red.jpg", price:69.99},
    {name: "podkoszulek social savage", image:"/products/female/tshirt_social_savage.jpg", price:69.99},
    {name: "podkoszulek vogue", image:"/products/female/tshirt_vogue.jpg", price:69.99},
    {name: "podkoszulek biały", image:"/products/female/tshirt_white.jpg", price:69.99},
    {name: "podkoszulek biały", image:"/products/female/tshirt_white_2.jpg", price:69.99},
    {name: "podkoszulek żółty", image:"/products/female/tshirt_yellow.jpg", price:69.99}
];